const xingamentos = [
  "burro",
  "burra",
  "idiota",
  "imbecil",
  "inútil",
  "babaca",
  "cretino",
  "cretina",
  "irritante",
  "chato",
  "chata",
  "cretino de merda",
  "seu bobo",
  "seu otário",
  "imbecil da porra",
  "seu estúpido",
  "vagabundo",
  "vagabunda",
  "merda",
  "caralho",
  "porra",
  "puta que pariu",
  "desgraçado",
  "desgraçada",
  "cabrão",
  "cabrao",
  "namoral",
  "babaca do caralho",
  "palhaço",
  "palhaça",
  "escroto",
  "escrota",
  "desculpa",
  "foda-se",
  "foda-se você",
  "vai se foder",
  "vai tomar no cu",
  "seu arrombado",
  "seu filho da puta",
  "seu merda",
  "cara de pau",
  "ridículo",
  "ridícula",
  "patético",
  "patética",
  "chifrudo",
  "chifruda",
  "otário",
  "otária",
  "viado",
  "viadozinho",
  "viado burro",
  "viado de merda",
  "bicha",
  "bicha do caralho",
  "viado do caralho",
  "cuzão",
  "cuzao",
  "cu",
  "pau no cu",
  "fedorento",
  "fedida",
  "fedido",
  "lixo",
  "lixo humano",
  "maldito",
  "maldita",
  "desgraça",
  "imbecil de merda",
  "você é lixo",
  "nojento",
  "nojenta",
  "babaca do p...",
  "raça ruim",
  "enfia",
  "enfia no cu",
  "enche o saco",
  "enche o saco de merda",
  "palhaço do caralho",
  "droga",
  "vá embora",
  "vai se ferrar",
  "vai se danar",
  "vai catar coquinho",
];

const expressionsCommands = new Map([
  ["fique bravo", "angry"],
  ["acorde", "awake"],
  ["vai programar", "code"],
  ["vamos tomar um café", "coffee"],
  ["coma", "eat"],
  ["vai para academia", "exercise"],
  ["fique feliz", "happy"],
  ["monte um cubo mágico", "playcube"],
  ["jogue videogame", "playvideogame"],
  ["leia um livro", "readbook"],
  ["leia as notícias", "readnews"],
  ["fique triste", "sad"],
  ["durma", "sleep"],
  ["assista tv", "watchtv"],
  ["assista um filme", "watchmovie"],
  ["sorria", "happy"],
]);

const openSettingsCommands = [
  "abrir configurações",
  "abrir a configuração",
  "abrir o painel de configurações",
  "entrar nas configurações",
  "mostrar configurações",
  "mostrar as configurações",
  "acessar configurações",
  "acessar as configurações",
  "configurações",
  "definir configurações",
  "ajustes",
  "abrir ajustes",
  "mostrar ajustes",
  "ir para as configurações",
  "ir para ajustes",
  "configuração do sistema",
  "abri configuração",
  "quer abrir configurações",
  "quero abrir configurações",
  "quero acessar configurações",
  "mostrar painel de configurações",
];

const closeSettingsCommands = [
  "fechar configurações",
  "fechar a configuração",
  "sair das configurações",
  "voltar das configurações",
  "fechar painel de configurações",
  "sair do painel de configurações",
  "fechar menu",
  "fechar o menu",
  "sair do menu",
  "fechar ajustes",
  "sair dos ajustes",
  "voltar dos ajustes",
  "fecha configurações",
  "fecha o menu",
  "encerra configurações",
  "encerra o menu"
];
